---
rules:
  no-unused-vars:
    - off
  "@typescript-eslint/no-unused-vars":
    - error
overrides:
  - files:
      - "*.test.ts"
      - "*.test.tsx"
    env:
      jest: true
globals:
  page: true
  browser: true
  context: true
  jestPuppeteer: true
