/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

export enum Dificulty {
  easy = "easy",
  hard = "hard",
  medium = "medium",
}

export enum Duration {
  long = "long",
  normal = "normal",
  short = "short",
}

export enum Ickyness {
  chicken = "chicken",
  frog = "frog",
  tepid = "tepid",
}

export enum Priority {
  high = "high",
  low = "low",
  medium = "medium",
}

/**
 * Autogenerated input type of CreateNewTaskMutation
 */
export interface CreateNewTaskMutationInput {
  task: CreateTaskInput;
  clientMutationId?: string | null;
}

export interface CreateTaskInput {
  title: string;
  description: string;
  priority: Priority;
  duration: Duration;
  dificulty: Dificulty;
  ickyness: Ickyness;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
